name: Renovate
on:
  workflow_dispatch: {}
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.21.0
        env:
          RENOVATE_AUTODISCOVER: "false"
          RENOVATE_OPTIMIZE_FOR_DISABLED: "true"
          RENOVATE_REQUIRE_CONFIG: "true"
          RENOVATE_ONBOARDING: "false"
          LOG_LEVEL: debug
          RENOVATE_GIT_AUTHOR: Renovate Bot <jikoh52603@veb34.com>
          RENOVATE_IGNORE_PR_AUTHOR: "true"
          RENOVATE_BRANCH_PREFIX: "renovate/"
          READONLY_GITLAB_LOOKUP_TOKEN: ${{ secrets.GITLAB_LOOKUP_TOKEN }}
          RENOVATE_REPOSITORIES: rv2673/renovate-gitlab-changelog-test
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
